-- AlterTable
ALTER TABLE "chapters" ALTER COLUMN "number" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "mangas" ALTER COLUMN "lastChapter" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "prefills" ALTER COLUMN "chapter" SET DATA TYPE DOUBLE PRECISION;
